service: strapi-staging
runtime: custom
env: flex
env_variables:
  DATABASE_NAME: "strapi_db"
  DATABASE_USER: "postgres"
  DATABASE_PASSWORD: "[password]"
  INSTANCE_CONNECTION_NAME: "jewelry-store-123456:us-central1:jewelry-store-db"
  API_TOKEN_SALT: "your-token-salt"
  ADMIN_JWT_SECRET: "your-jwt-secret"
  HOST: "0.0.0.0"
  PORT: 1337
  NODE_ENV: "production"
beta_settings:
  cloud_sql_instances: "jewelry-store-123456:us-central1:jewelry-store-db"
vpc_access_connector:
  name: "projects/jewelry-store-123456/locations/us-central1/connectors/jewelry-store-connector"
