name: Deploy Tharara CMS
on:
  push:
    branches:
      - main
      - test
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy tharara-cms-${{ github.ref_name == 'main' && 'prod' || 'test' }} \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/tharara-cms:latest \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated \
            --set-env-vars "DATABASE_URL=${{ github.ref_name == 'main' && secrets.PROD_DATABASE_URL || secrets.TEST_DATABASE_URL }}" \
            --set-env-vars "GCS_BUCKET=${{ github.ref_name == 'main' && secrets.PROD_GCS_BUCKET || secrets.TEST_GCS_BUCKET }}" \
            --set-env-vars "APP_KEYS=${{ secrets.STRAPI_APP_KEYS }}" \
            --set-env-vars "API_TOKEN_SALT=${{ secrets.STRAPI_API_TOKEN_SALT }}" \
            --set-env-vars "ADMIN_JWT_SECRET=${{ secrets.STRAPI_ADMIN_JWT_SECRET }}" \
            --set-env-vars "JWT_SECRET=${{ secrets.STRAPI_JWT_SECRET }}" \
            --set-env-vars "NODE_ENV=${{ github.ref_name == 'main' && 'production' || 'test' }}"
